#################################################################
# Makefile generated by Xilinx Platform Studio SDK
#                                                          
# WARNING : This file will be re-generated every time the
# FPGA is Programmed. So, any changes made to this file
# manually will be lost.
#################################################################

MHSFILE = D:/gpu_test_v3_1122_20110621/gpu_test_20110813/cpu_0/cpu_0.mhs
SYSTEM_BMM = implementation/cpu_0_bd.bmm
SYSTEM_BIT = implementation/cpu_0.bit
SDK_IMPLEMENTATION_DIR = D:/gpu_test_v3_1122_20110621/gpu_test_20110813/cpu_0/SDK_projects/implementation
SDK_DOWNLOAD_BIT = ${SDK_IMPLEMENTATION_DIR}/download_sdk.bit
SDK_DOWNLOAD_CMD = ${SDK_IMPLEMENTATION_DIR}/download_sdk.cmd
SEARCHPATHOPT = 
BRAMINIT_ELF_FILES = C:/Xilinx/10.1/EDK/sw/lib/microblaze/mb_bootloop.elf

all: download 

download: $(SDK_DOWNLOAD_BIT) dummy
	@echo "*********************************************"
	@echo "Downloading Bitstream onto the target board"
	@echo "*********************************************"
	impact -batch ${SDK_DOWNLOAD_CMD}
	@echo "Done!"

$(SDK_DOWNLOAD_BIT): $(SYSTEM_BIT) $(BRAMINIT_ELF_FILES) 
	@echo "*********************************************"
	@echo "Initializing BRAM contents of the bitstream"
	@echo "*********************************************"
	bitinit $(MHSFILE) $(SEARCHPATHOPT) -bm $(SYSTEM_BMM) -bt $(SYSTEM_BIT) \
	-o $(SDK_DOWNLOAD_BIT)  -pe microblaze_0 C:/Xilinx/10.1/EDK/sw/lib/microblaze/mb_bootloop.elf

clean: 
	rm -rf $(SDK_DOWNLOAD_BIT)

dummy: 
	@echo "" 

.PHONY: dummy 

